name: Run GoReleaser

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources
        uses: actions/checkout@v2
      - name: Install Protobuf Compiler
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.22'
      - name: Set up Protobuf Compiler in Go environment
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - name: Generate protobuf language bindings
        run: |
          make all
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
